In [1]:
import numpy as np
import math
import FitVec as fv

In [42]:
X = np.array([[0,0,1],[0,1,1],[1,0,1],[1,1,1]])
y = np.array([[0, 1, 1, 0]]).T
init_theta = 10*(np.random.random((13,1)) - 0.5) 

def runForward(X, theta):
	theta1 = np.array(theta[:9]).reshape(3,3)
	theta2 = np.array(theta[9:]).reshape(4,1)
	h1 = sigmoid(np.dot(X, theta1)) 
	h1_bias = np.insert(h1, 3, [1,1,1,1], axis=1)
	output = sigmoid(np.dot(h1_bias, theta2)) 
	return output
	#4x3 * 3x1 = 4x1
def costFunction(X, y, theta):
	m = float(len(X))
	hThetaX = np.array(runForward(X, theta))
	return np.sum(np.abs(y - hThetaX))
def sigmoid(x): return 1 / (1 + np.exp(- x))

def demoRun():
	print("Random theta: \n%s\n" % (np.round(runForward(X, init_theta), 2)))
	print("Cost: %s\n" % (costFunction(X,y, init_theta)))
	optimal_theta = fv.evolveParams(costFunction, 13, (100,0.01,50), X, y)
	print("Optimal theta: \n%s\n" % (np.round(runForward(X, optimal_theta.reshape(13,1)), 2)))
	print("Cost: %s\n" % (costFunction(X, y, optimal_theta.reshape(13,1))))
demoRun()

Random theta: 
[[ 0.02]
 [ 0.01]
 [ 0.01]
 [ 0.01]]

Cost: 2.00215947064

Optimal theta: 
[[ 0.]
 [ 1.]
 [ 1.]
 [ 0.]]

Cost: 3.46877223605e-08



In [82]:
def recombineVectors(arr):
    #arr is a 2-dimensional array of vectors
    #Steps:
    # 1. Choose first pair of vectors: indices 0, 1
    # 2. Pick random "cut point" along length of vector
    # 3. Swap corresponding vector subsets; move on to second pair of vectors, indices: 2,3
    resultVec = np.zeros(arr.shape, dtype="int64")
    arrLen = int((arr.shape[0]/2))
    for i in range(arrLen):
        x = 2*i;
        a = arr[x]
        b = arr[x+1]
        cutPt = np.random.randint(len(a))
        new_a = np.concatenate((a[0:cutPt], b[cutPt:]))
        new_b = np.concatenate((b[0:cutPt], a[cutPt:]))
        resultVec[x] = new_a
        resultVec[x+1] = new_b
    return resultVec

In [83]:
a = np.array([[1,3,4,5],[6,7,8,9],[10,11,12,13],[14,15,16,17]])
a

array([[ 1,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13],
       [14, 15, 16, 17]])

In [84]:
recombineVectors(a).dtype

dtype('int64')

In [7]:
a = np.zeros(a.shape)

In [20]:
b = a = np.array([[1,3,4,5],[6,7,8,9],[10,11,12,13]])

In [80]:
(np.random.permutation(a)).dtype

dtype('int64')